config/routes.rb
OnlinePayment::Application.routes.draw do

  resources :payments


  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/payment.rb
class Payment < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

	def index
		@payments = Payment.all
	end

	def new
		@payment = Payment.new
	end

	def create
		@payment = Payment.create(payment_params)

		if @payment.save
			redirect_to "/payments"
		else
			render "payments"
		end
	end

	private

	def payment_params
		params.require(:payment).permit(:first_name, :last_name, :account_number,
																		:address, :city, :state, :zip, :phone)
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Online Payment App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/payments">Capital Processing Online</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div id="wrap">
		<div class="container">
			<%= yield %>
		</div>
	</div>

  <div id="footer">
    <div class="container">
      <p class="text-muted credit">Online Payment System by <a href="http://capital-processing.com">Capital Processing Int'l Inc.</a></p>
    </div>
  </div>

</body>
</html>

app/views/payments/index.html.erb
<!DOCTYPE html>
<head>
	<title></title>
</head>

<body>
	<h1>Welcome to the Online Payment App</h1>

	<p>
		Click the payment button below to get started:
	</p> 

	<%= button_to "Make A Payment", new_payment_path, method: "get" %> 

</body>

app/views/payments/new.html.erb
<!DOCTYPE html>
<head>
	<title></title>
</head>

<body>

	<p>
		Please be sure to enter your information CORRECTLY:
	</p> 

	<p>
		<%= simple_form_for(Payment.new, html: {class: 'form-horizontal'}) do |f| %>

			<% if Payment.new.errors.any? %>
				<h3>Errors:</h3>
					<ul>
						<% @payment.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
			<% end %>

			<%= f.input	:first_name %>
			<%= f.input	:last_name %>
			<%= f.input	:account_number %>
			<%= f.input	:address %>
			<%= f.input	:city %>
			<%= f.input	:state %>
			<%= f.input :zip %>
			<%= f.input :phone %>
		</p>		
					
			<%= f.submit "Submit Payment" %>
		<% end %>
	<p class="footer">
		<%= button_to "Cancel", payments_path, method: "get" %>
	</p>
</body>